[build]
command = """
apt-get update && apt-get install -y wget
wget -q -O - https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
./zola build
"""
